# Generated by Django 3.1.6 on 2021-02-08 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Your snippet', max_length=50)),
                ('code', models.TextField()),
                ('lang', models.CharField(choices=[('text', 'None'), ('Python', 'python'), ('JavaScript', 'javascript')], default='text', max_length=18)),
                ('secret', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
                'db_table': 'Snippets',
            },
        ),
    ]
