# Generated by Django 3.1.6 on 2021-02-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_code', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='password',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='secret',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(default='Write your code here'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('Text', 'None'), ('Python', 'Python'), ('JavaScript', 'Javascript')], default='Text', max_length=18),
        ),
    ]
